version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_DEBUG=1
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db